// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Aobus Contributors

#include "test/fatal/LibraryProbeProtocol.h"

#include <array>
#include <span>

namespace ao::library::test
{
  std::span<LibraryFatalProbeExpectation const> libraryFatalProbeExpectations() noexcept
  {
    static constexpr auto kExpectations = std::array{
      LibraryFatalProbeExpectation{"list-builder-invalid-view",
                                   "expects",
                                   "view.isValid()",
                                   "Cannot prepare a List from an invalid view",
                                   "ListBuilder.cpp:",
                                   "ListBuilder::fromView"},
      LibraryFatalProbeExpectation{"manifest-builder-invalid-view",
                                   "expects",
                                   "view.isValid()",
                                   "Cannot prepare a file manifest from an invalid view",
                                   "FileManifestBuilder.cpp:",
                                   "FileManifestBuilder::fromView"},
      LibraryFatalProbeExpectation{"manifest-bind-zero-track",
                                   "expects",
                                   "id != kInvalidTrackId",
                                   "Cannot bind a file manifest to Track zero",
                                   "FileManifestBuilder.cpp:",
                                   "FileManifestBuilder::Unbound::bind"},
      LibraryFatalProbeExpectation{"manifest-bind-consumed",
                                   "expects",
                                   "_header.trackId == kInvalidTrackId",
                                   "Cannot bind a file manifest that was already bound",
                                   "FileManifestBuilder.cpp:",
                                   "FileManifestBuilder::Unbound::bind"},
      LibraryFatalProbeExpectation{"list-store-zero-update",
                                   "expects",
                                   "id != kInvalidListId",
                                   "Cannot update the reserved List id zero",
                                   "ListStore.cpp:",
                                   "ListStore::Writer::update",
                                   true},
      LibraryFatalProbeExpectation{"track-writer-after-commit",
                                   "expects",
                                   "(_implPtr != nullptr && _implPtr->transaction.isActive())",
                                   "Library write transaction is no longer active",
                                   "WriteTransaction.cpp:",
                                   "WriteTransaction::requireOperationActive",
                                   true},
      LibraryFatalProbeExpectation{"track-writer-after-apply",
                                   "expects",
                                   "_implPtr->operationActive",
                                   "Library mutation is outside its apply operation",
                                   "WriteTransaction.cpp:",
                                   "WriteTransaction::requireOperationActive",
                                   true},
      LibraryFatalProbeExpectation{
        "post-open-native-read-failure", "fatal", {}, "mdb_get", "ThrowError.cpp:", "failRead", true},
      LibraryFatalProbeExpectation{"post-open-track-reader-half-row",
                                   "invariant",
                                   "optHotBytes.has_value() == optColdBytes.has_value()",
                                   "Track hot/cold presence diverged after library validation",
                                   "TrackStore.cpp:",
                                   "TrackStore::Reader::get",
                                   true},
      LibraryFatalProbeExpectation{"post-open-track-writer-half-row",
                                   "invariant",
                                   "optHotBytes.has_value() == optColdBytes.has_value()",
                                   "Track hot/cold presence diverged after library validation",
                                   "TrackStore.cpp:",
                                   "TrackStore::Writer::get",
                                   true},
      LibraryFatalProbeExpectation{"lmdb-read-fault-injection-unconsumed",
                                   "fatal",
                                   {},
                                   "Injected LMDB read failure was not consumed",
                                   "ThrowError.cpp:",
                                   "ReadFaultInjection::~ReadFaultInjection"},
      LibraryFatalProbeExpectation{"post-open-list-corruption",
                                   "invariant",
                                   "view.isValid()",
                                   "record is structurally corrupt after library validation",
                                   "ListStore.cpp:",
                                   "ListStore::Reader::get",
                                   true},
      LibraryFatalProbeExpectation{"post-open-list-parent-breach",
                                   "invariant",
                                   "optParent",
                                   "List parent chain refers to missing List 999 after library validation",
                                   "ListWriter.cpp:",
                                   "ListWriter::validateParent",
                                   true},
      LibraryFatalProbeExpectation{"post-open-list-parent-cycle",
                                   "invariant",
                                   "inserted",
                                   "List parent graph contains a cycle after library validation",
                                   "ListWriter.cpp:",
                                   "ListWriter::validateParent",
                                   true},
      LibraryFatalProbeExpectation{"post-open-manifest-binding-breach",
                                   "invariant",
                                   "optManifest",
                                   "has no manifest binding",
                                   "TrackWriter.cpp:",
                                   "requireManifestBinding",
                                   true},
      LibraryFatalProbeExpectation{"revision-exhaustion",
                                   "invariant",
                                   "metadataSnapshot.revision < std::numeric_limits<std::uint64_t>::max() - 1U",
                                   "Library revision space is exhausted",
                                   "WriteTransaction.cpp:",
                                   "WriteTransaction::begin",
                                   true},
      LibraryFatalProbeExpectation{"cross-library-write-revision",
                                   "expects",
                                   "_implPtr->identity == &identity",
                                   "Write transaction belongs to a different MusicLibrary",
                                   "WriteTransaction.cpp:",
                                   "WriteTransaction::libraryRevision",
                                   true},
      LibraryFatalProbeExpectation{"cross-library-operation-metadata",
                                   "expects",
                                   "_implPtr->identity == &identity",
                                   "Write transaction belongs to a different MusicLibrary",
                                   "WriteTransaction.cpp:",
                                   "WriteTransaction::metadataHeader",
                                   true},
      LibraryFatalProbeExpectation{"lmdb-reader-moved-from",
                                   "expects",
                                   "transaction.isActive()",
                                   "IntegerKeyDatabase::Reader created from an inactive transaction",
                                   "Database.cpp:",
                                   "IntegerKeyDatabase::reader",
                                   true},
      LibraryFatalProbeExpectation{"lmdb-writer-after-commit",
                                   "expects",
                                   "_txn != nullptr && _txn->isActive()",
                                   "IntegerKeyDatabase::Writer used after its transaction finished",
                                   "Database.cpp:",
                                   "IntegerKeyDatabase::Writer::ensureActive",
                                   true},
      LibraryFatalProbeExpectation{"lmdb-writer-from-finished",
                                   "expects",
                                   "_txn != nullptr && _txn->isActive()",
                                   "IntegerKeyDatabase::Writer used after its transaction finished",
                                   "Database.cpp:",
                                   "IntegerKeyDatabase::Writer::ensureActive",
                                   true},
      LibraryFatalProbeExpectation{"lmdb-reader-after-write-commit",
                                   "expects",
                                   "_owner != nullptr && _owner->isActive()",
                                   "IntegerKeyDatabase::Reader used after its transaction finished",
                                   "Database.cpp:",
                                   "IntegerKeyDatabase::Reader::ensureActive",
                                   true},
      LibraryFatalProbeExpectation{"lmdb-iterator-after-write-commit",
                                   "expects",
                                   "_owner != nullptr && _owner->isActive()",
                                   "IntegerKeyDatabase::Reader::Iterator used after its transaction finished",
                                   "Database.cpp:",
                                   "IntegerKeyDatabase::Reader::Iterator::ensureActive",
                                   true},
      LibraryFatalProbeExpectation{"lmdb-invalid-integer-key",
                                   "invariant",
                                   "size() == sizeof(std::uint32_t)",
                                   "LMDB integer key has an invalid size",
                                   "Database.cpp:",
                                   "IntegerKeyDatabase::Reader::KeyView::operator",
                                   true},
      LibraryFatalProbeExpectation{"nested-apply",
                                   "expects",
                                   "!_implPtr->operationActive",
                                   "Library write transaction already has an active operation",
                                   "WriteTransaction.cpp:",
                                   "WriteTransaction::applyBoundary",
                                   true},
      LibraryFatalProbeExpectation{"commit-during-apply",
                                   "expects",
                                   "!_implPtr->operationActive",
                                   "Cannot commit during a library write operation",
                                   "WriteTransaction.cpp:",
                                   "WriteTransaction::commit",
                                   true},
      LibraryFatalProbeExpectation{"terminated-during-apply",
                                   "invariant",
                                   "(_implPtr != nullptr && _implPtr->transaction.isActive())",
                                   "Library write operation terminated its transaction",
                                   "WriteTransaction.cpp:",
                                   "WriteTransaction::applyBoundary",
                                   true},
      LibraryFatalProbeExpectation{"terminated-during-failed-apply",
                                   "invariant",
                                   "(_implPtr != nullptr && _implPtr->transaction.isActive())",
                                   "Library write operation terminated its transaction",
                                   "WriteTransaction.cpp:",
                                   "WriteTransaction::applyBoundary",
                                   true},
      LibraryFatalProbeExpectation{"terminated-during-throw",
                                   "invariant",
                                   "(_implPtr != nullptr && _implPtr->transaction.isActive())",
                                   "Library write operation terminated its transaction",
                                   "WriteTransaction.cpp:",
                                   "WriteTransaction::applyBoundary",
                                   true},
    };

    return kExpectations;
  }

  std::span<LibraryProbeObservationExpectation const> libraryProbeObservationExpectations() noexcept
  {
    static constexpr auto kExpectations = std::array{
      LibraryProbeObservationExpectation{
        "normal-observation", "observation=probe-ready", "Library probe diagnostic-only marker"},
    };

    return kExpectations;
  }
} // namespace ao::library::test
