// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Aobus Contributors

#include "test/fatal/RuntimeFatalProbeProtocol.h"

#include <array>
#include <span>
#include <string_view>

namespace ao::rt::test
{
  std::span<RuntimeFatalProbeExpectation const> runtimeFatalProbeExpectations() noexcept
  {
    static constexpr auto kExpectations = std::array{
      RuntimeFatalProbeExpectation{"yaml-export-missing-cover-resource",
                                   "invariant",
                                   "optDescriptor",
                                   "cover references missing Resource",
                                   "LibraryYamlExporter.cpp:",
                                   "collectReachableResources",
                                   {},
                                   {}},
      RuntimeFatalProbeExpectation{"library-publication-admission-exception",
                                   "unhandled-exception",
                                   {},
                                   "library publication failure: phase=admission library='",
                                   "LibraryChanges.cpp:",
                                   "publish",
                                   "slice-h-publication-library",
                                   "revision=1 replica='ProbeReplica': probe publication admission rejection"},
      RuntimeFatalProbeExpectation{"library-publication-replica-exception",
                                   "unhandled-exception",
                                   {},
                                   "library publication failure: phase=replica-apply library='",
                                   "LibraryChanges.cpp:",
                                   "deliverPending",
                                   "slice-h-publication-library",
                                   "revision=1 replica='ProbeReplica': probe publication replica exception"},
      RuntimeFatalProbeExpectation{"library-publication-observer-exception",
                                   "unhandled-exception",
                                   {},
                                   "library publication failure: phase=observer-delivery library='",
                                   "LibraryChanges.cpp:",
                                   "connectObserver",
                                   "slice-h-publication-library",
                                   "revision=1 replica='ProbeReplica': probe publication observer exception"},
      RuntimeFatalProbeExpectation{"library-publication-completion-exception",
                                   "unhandled-exception",
                                   {},
                                   "library publication failure: phase=completion library='",
                                   "LibraryWriteLane.cpp:",
                                   "onAvailabilityChanged",
                                   "slice-h-publication-library",
                                   "revision=1 replica='ProbeReplica': probe publication completion exception"},
      RuntimeFatalProbeExpectation{"library-publication-completion-ack-invariant",
                                   "fatal",
                                   {},
                                   "library publication failure: phase=completion-ack library='",
                                   "LibraryWriteLane.cpp:",
                                   "requireMatchingPublicationCompletion",
                                   "slice-h-publication-library",
                                   "revision=1 replica='ProbeReplica' committed-revision=1 publication-active=false"},
      RuntimeFatalProbeExpectation{"library-mutation-execute-after-apply",
                                   "invariant",
                                   "_executeEligible",
                                   "Library mutation execute must own the first write operation",
                                   "LibraryWriteLane.h:",
                                   "execute",
                                   {},
                                   {}},
      RuntimeFatalProbeExpectation{"library-mutation-prestamped-changeset",
                                   "invariant",
                                   "changeSet.libraryRevision == 0",
                                   "Library operation produced a pre-stamped change set",
                                   "LibraryWriteLane.cpp:",
                                   "commitMutation",
                                   {},
                                   {}},
      RuntimeFatalProbeExpectation{"operation-cancelled-empty-rethrow",
                                   "expects",
                                   "exceptionPtr",
                                   "Cannot rethrow an empty exception",
                                   "OperationCancelled.cpp:",
                                   "rethrowException",
                                   {},
                                   {}},
      RuntimeFatalProbeExpectation{"runtime-spawn-logged-exception",
                                   "unhandled-exception",
                                   {},
                                   "runtime spawnLogged probe: probe exception",
                                   "Runtime.cpp:",
                                   "finishFireAndForget",
                                   {},
                                   {}},
      RuntimeFatalProbeExpectation{"runtime-cancellable-exception",
                                   "unhandled-exception",
                                   {},
                                   "runtime cancellable probe: probe exception",
                                   "Runtime.cpp:",
                                   "finishFireAndForget",
                                   {},
                                   {}},
      RuntimeFatalProbeExpectation{"runtime-lifetime-exception",
                                   "unhandled-exception",
                                   {},
                                   "runtime lifetime probe: probe exception",
                                   "Runtime.cpp:",
                                   "finishFireAndForget",
                                   "probe-scope-empty=true",
                                   {}},
      RuntimeFatalProbeExpectation{"runtime-shutdown-exception",
                                   "unhandled-exception",
                                   {},
                                   "runtime shutdown probe: probe exception",
                                   "Runtime.cpp:",
                                   "finishFireAndForget",
                                   "probe-scope-empty=true",
                                   "probe-shutdown-started=true"},
      RuntimeFatalProbeExpectation{"queued-executor-callback-exception",
                                   "unhandled-exception",
                                   {},
                                   "queued executor callback: probe exception",
                                   "QueuedExecutorBase.cpp:",
                                   "drainQueuedTasks",
                                   "probe-queue-bookkeeping=true",
                                   {}},
      RuntimeFatalProbeExpectation{"queued-executor-final-drain-limit",
                                   "fatal",
                                   {},
                                   "Queued executor final drain did not reach quiescence after 1024 turns",
                                   "QueuedExecutorBase.cpp:",
                                   "drainQueuedTasksUntilIdle",
                                   {},
                                   {}},
      RuntimeFatalProbeExpectation{"playback-publication-admission-exception",
                                   "unhandled-exception",
                                   {},
                                   "playback snapshot-publication admission: probe defer rejection",
                                   "PlaybackService.cpp:",
                                   "scheduleDeferredPublish",
                                   {},
                                   {}},
      RuntimeFatalProbeExpectation{"playback-command-drain-admission-exception",
                                   "unhandled-exception",
                                   {},
                                   "playback command-drain admission: probe defer rejection",
                                   "PlaybackService.cpp:",
                                   "scheduleCommandDrain",
                                   {},
                                   {}},
      RuntimeFatalProbeExpectation{"playback-command-exception",
                                   "unhandled-exception",
                                   {},
                                   "queued executor callback: probe playback command exception",
                                   "QueuedExecutorBase.cpp:",
                                   "drainQueuedTasks",
                                   "probe-playback-closed=true",
                                   {}},
      RuntimeFatalProbeExpectation{"playback-reveal-off-executor",
                                   "expects",
                                   "executor.isCurrent()",
                                   "PlaybackTransport invoked off the executor thread",
                                   "PlaybackTransport.cpp:",
                                   "revealPlayingTrack",
                                   {},
                                   {}},
      RuntimeFatalProbeExpectation{"playback-service-snapshot-off-executor",
                                   "expects",
                                   "executor.isCurrent()",
                                   "PlaybackService invoked off the executor thread",
                                   "PlaybackService.cpp:",
                                   "snapshot",
                                   {},
                                   {}},
      RuntimeFatalProbeExpectation{"playback-service-command-off-executor",
                                   "expects",
                                   "executor.isCurrent()",
                                   "PlaybackService invoked off the executor thread",
                                   "PlaybackService.cpp:",
                                   "setMuted",
                                   {},
                                   {}},
      RuntimeFatalProbeExpectation{"playback-service-event-off-executor",
                                   "expects",
                                   "executor.isCurrent()",
                                   "PlaybackService invoked off the executor thread",
                                   "PlaybackService.cpp:",
                                   "onSnapshot",
                                   {},
                                   {}},
      RuntimeFatalProbeExpectation{"workspace-observation-admission-exception",
                                   "unhandled-exception",
                                   {},
                                   "workspace observation admission: probe defer rejection",
                                   "WorkspaceService.cpp:",
                                   "publish",
                                   {},
                                   {}},
      RuntimeFatalProbeExpectation{"view-projection-observation-admission-exception",
                                   "unhandled-exception",
                                   {},
                                   "view projection observation admission for view 1: probe defer rejection",
                                   "ViewService.cpp:",
                                   "setFilter",
                                   {},
                                   {}},
      RuntimeFatalProbeExpectation{"view-presentation-observation-admission-exception",
                                   "unhandled-exception",
                                   {},
                                   "view presentation observation admission for view 1: probe defer rejection",
                                   "ViewService.cpp:",
                                   "setPresentation",
                                   {},
                                   {}},
      RuntimeFatalProbeExpectation{"signal-connect-off-owner",
                                   "expects",
                                   "std::this_thread::get_id() == _ownerThread",
                                   "Signal invoked off the owner thread",
                                   "Signal.h:",
                                   "connect",
                                   {},
                                   {}},
      RuntimeFatalProbeExpectation{"signal-disconnect-off-owner",
                                   "expects",
                                   "std::this_thread::get_id() == _ownerThread",
                                   "Signal invoked off the owner thread",
                                   "Signal.h:",
                                   "disconnect",
                                   {},
                                   {}},
      RuntimeFatalProbeExpectation{"signal-emit-off-owner",
                                   "expects",
                                   "std::this_thread::get_id() == _ownerThread",
                                   "Signal invoked off the owner thread",
                                   "Signal.h:",
                                   "emit",
                                   {},
                                   {}},
      RuntimeFatalProbeExpectation{"signal-observer-exception",
                                   "unhandled-exception",
                                   {},
                                   "signal observer: probe exception",
                                   "Signal.h:",
                                   "emit",
                                   {},
                                   {}},
      RuntimeFatalProbeExpectation{"task-future-missing-result",
                                   "invariant",
                                   "result.hasValue()",
                                   "Task future completed without a result",
                                   "TaskFuture.h:",
                                   "get",
                                   {},
                                   {}},
#ifdef _WIN32
      RuntimeFatalProbeExpectation{"destructive-restart-release-exception",
                                   "unhandled-exception",
                                   {},
                                   "destructive restart active-graph release: probe exception",
                                   "DestructiveLibraryRestart.cpp:",
                                   "executeDestructiveLibraryRestart",
                                   "probe-successor-launched=true",
                                   {}},
      RuntimeFatalProbeExpectation{"destructive-restart-launch-exception",
                                   "unhandled-exception",
                                   {},
                                   "destructive restart successor launch: probe exception",
                                   "DestructiveLibraryRestart.cpp:",
                                   "executeDestructiveLibraryRestart",
                                   {},
                                   {}},
#endif
    };

    return kExpectations;
  }

  std::span<std::string_view const> runtimeCleanProbeScenarios() noexcept
  {
    static constexpr auto kScenarios = std::array{
      std::string_view{"runtime-shutdown-cancellation"},
      std::string_view{"library-control-delivery-closing-race"},
    };
    return kScenarios;
  }
} // namespace ao::rt::test
