# Test source registration is derived from configured CMake targets. Conditional
# sources use a single declaration through aobus_target_test_sources so disabled
# platform/frontend sources remain visible to the configure-time guard.

function(_aobus_normalize_test_source output source base_directory)
  if("${source}" MATCHES "\\$<")
    message(FATAL_ERROR
      "Test source generator expressions are unsupported because registration "
      "must resolve at configure time: ${source}")
  endif()

  cmake_path(IS_ABSOLUTE source _is_absolute)
  if(_is_absolute)
    cmake_path(NORMAL_PATH source OUTPUT_VARIABLE _absolute)
  else()
    cmake_path(ABSOLUTE_PATH source BASE_DIRECTORY "${base_directory}" NORMALIZE OUTPUT_VARIABLE _absolute)
  endif()
  cmake_path(RELATIVE_PATH _absolute BASE_DIRECTORY "${CMAKE_SOURCE_DIR}" OUTPUT_VARIABLE _relative)
  string(REPLACE "\\" "/" _relative "${_relative}")
  if(_relative MATCHES "^\\.\\./" OR NOT _relative MATCHES "^test/.+Test\\.(cpp|mm)$")
    message(FATAL_ERROR "Test source must be a *Test.cpp or *Test.mm file below test/: ${source}")
  endif()
  if(NOT EXISTS "${_absolute}")
    message(FATAL_ERROR "Declared test source does not exist: ${_relative}")
  endif()
  set(${output} "${_relative}" PARENT_SCOPE)
endfunction()

function(aobus_target_test_sources target enabled disabled_reason)
  if(enabled)
    if(NOT TARGET "${target}")
      message(FATAL_ERROR "Enabled test source target does not exist: ${target}")
    endif()
  elseif("${disabled_reason}" STREQUAL "" OR "${disabled_reason}" MATCHES "[;\t\r\n]")
    message(FATAL_ERROR "Disabled test sources require a single-line reason without semicolons")
  endif()

  foreach(_source IN LISTS ARGN)
    _aobus_normalize_test_source(_relative "${_source}" "${CMAKE_CURRENT_SOURCE_DIR}")
    if(NOT enabled)
      set_property(GLOBAL APPEND PROPERTY AOBUS_DISABLED_TEST_SOURCE_RECORDS
        "${_relative}\t${disabled_reason}")
    endif()
  endforeach()
  if(enabled)
    target_sources("${target}" PRIVATE ${ARGN})
  endif()
endfunction()

function(aobus_finalize_test_sources manifest)
  if(NOT IS_ABSOLUTE "${manifest}")
    message(FATAL_ERROR "Test source manifest path must be absolute: ${manifest}")
  endif()

  file(GLOB_RECURSE _expected CONFIGURE_DEPENDS LIST_DIRECTORIES false
    "${CMAKE_SOURCE_DIR}/test/*Test.cpp"
    "${CMAKE_SOURCE_DIR}/test/*Test.mm")
  list(FILTER _expected EXCLUDE REGEX "/test/integration/lint/fixture/")
  set(_expected_relative)
  foreach(_source IN LISTS _expected)
    _aobus_normalize_test_source(_relative "${_source}" "${CMAKE_SOURCE_DIR}")
    list(APPEND _expected_relative "${_relative}")
  endforeach()
  list(SORT _expected_relative)

  set(_configured)
  set(_records)
  foreach(_target IN LISTS ARGN)
    if(NOT TARGET "${_target}")
      continue()
    endif()
    get_target_property(_type "${_target}" TYPE)
    get_target_property(_imported "${_target}" IMPORTED)
    if(NOT _type STREQUAL "EXECUTABLE" OR _imported)
      message(FATAL_ERROR "Test source owner must be a non-imported executable: ${_target}")
    endif()
    get_target_property(_target_sources "${_target}" SOURCES)
    get_target_property(_target_source_dir "${_target}" SOURCE_DIR)
    if(NOT _target_sources)
      continue()
    endif()
    foreach(_source IN LISTS _target_sources)
      if("${_source}" MATCHES "\\$<")
        message(FATAL_ERROR
          "Test target ${_target} has an unsupported source generator expression: ${_source}")
      endif()
      if(NOT "${_source}" MATCHES "Test\\.(cpp|mm)$")
        continue()
      endif()
      _aobus_normalize_test_source(_relative "${_source}" "${_target_source_dir}")
      get_source_file_property(_header_only "${_source}" TARGET_DIRECTORY "${_target}" HEADER_FILE_ONLY)
      get_source_file_property(_external_object "${_source}" TARGET_DIRECTORY "${_target}" EXTERNAL_OBJECT)
      if(_header_only OR _external_object)
        message(FATAL_ERROR "Test source must be compiled, not header-only or an external object: ${_relative}")
      endif()
      list(FIND _configured "${_relative}" _existing)
      if(NOT _existing EQUAL -1)
        message(FATAL_ERROR
          "Test source belongs to more than one executable or is listed more than once: ${_relative}")
      endif()
      list(APPEND _configured "${_relative}")
      list(APPEND _records "${_relative}\tconfigured\t${_target}")
    endforeach()
  endforeach()

  get_property(_disabled_records GLOBAL PROPERTY AOBUS_DISABLED_TEST_SOURCE_RECORDS)
  set(_disabled)
  foreach(_record IN LISTS _disabled_records)
    string(REPLACE "\t" ";" _fields "${_record}")
    list(GET _fields 0 _source)
    list(GET _fields 1 _reason)
    list(FIND _disabled "${_source}" _disabled_existing)
    if(NOT _disabled_existing EQUAL -1)
      message(FATAL_ERROR "Disabled test source is declared more than once: ${_source}")
    endif()
    list(FIND _configured "${_source}" _configured_existing)
    if(NOT _configured_existing EQUAL -1)
      message(FATAL_ERROR "Test source is both configured and disabled: ${_source}")
    endif()
    list(APPEND _disabled "${_source}")
    list(APPEND _records "${_source}\tdisabled\t${_reason}")
  endforeach()

  set(_declared ${_configured} ${_disabled})
  list(SORT _declared)
  if(NOT _declared STREQUAL _expected_relative)
    set(_missing ${_expected_relative})
    list(REMOVE_ITEM _missing ${_declared})
    set(_unexpected ${_declared})
    list(REMOVE_ITEM _unexpected ${_expected_relative})
    if(_missing)
      list(JOIN _missing "\n  " _missing_text)
      set(_missing_message "\nMissing test target sources:\n  ${_missing_text}")
    endif()
    if(_unexpected)
      list(JOIN _unexpected "\n  " _unexpected_text)
      set(_unexpected_message "\nUnexpected test source declarations:\n  ${_unexpected_text}")
    endif()
    message(FATAL_ERROR "Test source registration does not match this configuration.${_missing_message}${_unexpected_message}")
  endif()

  # This is configuration evidence for inspection, not proof of compilation or execution.
  # Reconfiguration owns its freshness; there is no second source registry.
  list(SORT _records)
  set(_contents "source\tstate\towner-or-disabled-reason\n")
  foreach(_record IN LISTS _records)
    string(APPEND _contents "${_record}\n")
  endforeach()
  file(WRITE "${manifest}" "${_contents}")
endfunction()
